baseURL = 'https://mattischrome.com/'
languageCode = 'en-gb'
title = 'mattischrome'
theme = 'doorman'
[params]
  tableOfContents = false
  math = false
  recent_posts = true
  recent_posts_count = 6
  show_post_footer = true
  fleuron_image = '/images/divider.svg'
  rss = true
  source_url = 'https://github.com/mattischrome/console-blog'
  [params.posts]
    paginate = 12

  [params.photos]
    paginate = 12
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
